import type { Metadata } from "next";
import { Poppins, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const poppinsExtraBold = Poppins({
  variable: "--font-poppins",
  weight: "900",
  subsets: ["latin"],
});

const poppinsBold = Poppins({
  variable: "--font-poppins",
  weight: "700",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppinsBold.variable} ${poppinsExtraBold.variable} ${inter.variable} antialiased bg-background-200`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
